"""upgrade tables

Revision ID: 58fcffc037f6
Revises: 98bdc3940d26
Create Date: 2019-08-04 01:21:06.646286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fcffc037f6'
down_revision = '98bdc3940d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies__database_name', table_name='movies__database')
    op.create_index(op.f('ix_movies__database_name'), 'movies__database', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies__database_name'), table_name='movies__database')
    op.create_index('ix_movies__database_name', 'movies__database', ['name'], unique=False)
    # ### end Alembic commands ###
